export const PAYMENT_SPLIT_RECIPIENT_STATUS = {
  CREATED: 'created',
  PENDING_GATEWAY: 'pending_gateway',
  PROCESSING_GATEWAY: 'processing_gateway',

  TRANSFERRED: 'transferred',
  PARTIALLY_TRANSFERRED: 'partially_transferred',

  RETAINED: 'retained',

  REVERSED: 'reversed',
  PARTIALLY_REVERSED: 'partially_reversed',

  RETAINED_REVERSED: 'retained_reversed',
  RETAINED_PARTIALLY_REVERSED: 'retained_partially_reversed',

  FAILED: 'failed',
  REVERSAL_FAILED: 'reversal_failed',
} as const;

export type PaymentSplitRecipientStatus =
  (typeof PAYMENT_SPLIT_RECIPIENT_STATUS)[keyof typeof PAYMENT_SPLIT_RECIPIENT_STATUS];

export const PAYMENT_SPLIT_RECIPIENT_TRANSFERRED_STATUSES: PaymentSplitRecipientStatus[] =
  [
    PAYMENT_SPLIT_RECIPIENT_STATUS.TRANSFERRED,
    PAYMENT_SPLIT_RECIPIENT_STATUS.PARTIALLY_TRANSFERRED,
  ];

export const PAYMENT_SPLIT_RECIPIENT_RETAINED_STATUSES: PaymentSplitRecipientStatus[] =
  [
    PAYMENT_SPLIT_RECIPIENT_STATUS.RETAINED,
    PAYMENT_SPLIT_RECIPIENT_STATUS.RETAINED_REVERSED,
    PAYMENT_SPLIT_RECIPIENT_STATUS.RETAINED_PARTIALLY_REVERSED,
  ];

export const PAYMENT_SPLIT_RECIPIENT_REVERSED_STATUSES: PaymentSplitRecipientStatus[] =
  [
    PAYMENT_SPLIT_RECIPIENT_STATUS.REVERSED,
    PAYMENT_SPLIT_RECIPIENT_STATUS.PARTIALLY_REVERSED,
    PAYMENT_SPLIT_RECIPIENT_STATUS.RETAINED_REVERSED,
    PAYMENT_SPLIT_RECIPIENT_STATUS.RETAINED_PARTIALLY_REVERSED,
  ];