export const PAYMENT_SPLIT_STATUS = {
  CREATED: 'created',
  PENDING_GATEWAY: 'pending_gateway',
  PROCESSING_GATEWAY: 'processing_gateway',

  TRANSFERRED: 'transferred',
  PARTIALLY_TRANSFERRED: 'partially_transferred',

  REVERSED: 'reversed',
  PARTIALLY_REVERSED: 'partially_reversed',

  FAILED: 'failed',
  GATEWAY_FAILED_RETRYABLE: 'gateway_failed_retryable',
  GATEWAY_FAILED_PERMANENT: 'gateway_failed_permanent',

  CANCELLED: 'cancelled',
} as const;

export type PaymentSplitStatus =
  (typeof PAYMENT_SPLIT_STATUS)[keyof typeof PAYMENT_SPLIT_STATUS];

export const PAYMENT_SPLIT_DISPATCHABLE_STATUSES: PaymentSplitStatus[] = [
  PAYMENT_SPLIT_STATUS.CREATED,
  PAYMENT_SPLIT_STATUS.PENDING_GATEWAY,
  PAYMENT_SPLIT_STATUS.PROCESSING_GATEWAY,
  PAYMENT_SPLIT_STATUS.FAILED,
  PAYMENT_SPLIT_STATUS.PARTIALLY_TRANSFERRED,
  PAYMENT_SPLIT_STATUS.GATEWAY_FAILED_RETRYABLE,
];

export const PAYMENT_SPLIT_REVERSIBLE_STATUSES: PaymentSplitStatus[] = [
  PAYMENT_SPLIT_STATUS.TRANSFERRED,
  PAYMENT_SPLIT_STATUS.PARTIALLY_TRANSFERRED,
  PAYMENT_SPLIT_STATUS.PARTIALLY_REVERSED,
];

export const PAYMENT_SPLIT_FINAL_STATUSES: PaymentSplitStatus[] = [
  PAYMENT_SPLIT_STATUS.TRANSFERRED,
  PAYMENT_SPLIT_STATUS.REVERSED,
  PAYMENT_SPLIT_STATUS.CANCELLED,
  PAYMENT_SPLIT_STATUS.GATEWAY_FAILED_PERMANENT,
];