import type { PaymentTransactionEntity } from '../../../entities/payment-transaction.entity';

export class CreatePaymentTransactionDtoOut {
  constructor(
    public readonly id: number,
    public readonly _id: string,
    public readonly officeId: string,
    public readonly clientId: string,
    public readonly checkoutSessionId: string | null,
    public readonly paymentCustomerId: string | null,
    public readonly gatewayId: string,
    public readonly apiCredentialId: string | null,
    public readonly gatewayTransactionId: string | null,
    public readonly externalReference: string | null,
    public readonly idempotencyKey: string | null,
    public readonly paymentType: string,
    public readonly paymentMethod: string,
    public readonly amount: number,
    public readonly currency: string,
    public readonly installments: number | null,
    public readonly installmentAmount: number | null,
    public readonly interestAmount: number | null,
    public readonly interestType: string | null,
    public readonly gatewayStatus: string | null,
    public readonly status: string,
    public readonly processStatus: string,
    public readonly processMessage: string | null,
    public readonly providerPayload: Record<string, unknown> | null,
    public readonly providerResponse: Record<string, unknown> | null,
    public readonly gatewayResponse: Record<string, unknown> | null,
    public readonly qrCode: string | null,
    public readonly qrCodeBase64: string | null,
    public readonly boletoUrl: string | null,
    public readonly checkoutUrl: string | null,
    public readonly splitRequired: boolean,
    public readonly hasSplit: boolean,
    public readonly paidAt: string | null,
    public readonly authorizedAt: string | null,
    public readonly canceledAt: string | null,
    public readonly failedAt: string | null,
    public readonly refundedAt: string | null,
    public readonly expiresAt: string | null,
    public readonly metadata: Record<string, unknown> | null,
    public readonly config: Record<string, unknown> | null,
    public readonly changesHistory: Array<Record<string, unknown>> | null,
    public readonly createdAt: string | null,
    public readonly updatedAt: string | null,
  ) {}

  static fromEntity(
    entity: PaymentTransactionEntity,
  ): CreatePaymentTransactionDtoOut {
    return new CreatePaymentTransactionDtoOut(
      entity.id ?? 0,
      entity._id ?? '',
      entity.officeId,
      entity.clientId,
      entity.checkoutSessionId,
      entity.paymentCustomerId,
      entity.gatewayId,
      entity.apiCredentialId,
      entity.gatewayTransactionId,
      entity.externalReference,
      entity.idempotencyKey,
      entity.paymentType,
      entity.paymentMethod,
      entity.amount,
      entity.currency,
      entity.installments,
      entity.installmentAmount,
      entity.interestAmount,
      entity.interestType,
      entity.gatewayStatus,
      entity.status ?? 'created',
      entity.processStatus,
      entity.processMessage,
      entity.providerPayload,
      entity.providerResponse,
      entity.gatewayResponse,
      entity.qrCode,
      entity.qrCodeBase64,
      entity.boletoUrl,
      entity.checkoutUrl,
      entity.splitRequired,
      entity.hasSplit,
      entity.paidAt,
      entity.authorizedAt,
      entity.canceledAt,
      entity.failedAt,
      entity.refundedAt,
      entity.expiresAt,
      entity.metadata,
      entity.config,
      entity.changesHistory,
      entity.createdAt,
      entity.updatedAt,
    );
  }
}
